/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarComponent: typeof import('./components/AppBarComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavigationDrawerComponent: typeof import('./components/NavigationDrawerComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentComponent: typeof import('./components/ui/StudentComponent.vue')['default']
    StudentModal: typeof import('./components/ui/StudentModal.vue')['default']
  }
}
